<?php
/**
 * @file
 * Code for the TAS Dash feature.
 */

include_once 'tas_dash.features.inc';

/**
 * Implements hook_wsclient_service_load().
 * Not working. :(
 */
function tas_dash_wsclient_service_load($services) {
  //$credentials = variable_get('tas_dash_username') . ':' . variable_get('tas_dash_pass');
  $services['tas_dash']->settings['curl options'][CURLOPT_USERPWD] = '';
  //$apipass = variable_get('pingdom_api_appkey');
  $services['tas_dash']->settings['curl options'][CURLOPT_HTTPHEADER] = array('');
}

function tas_dash_wsclient_version($info = 'version') {
  $service = wsclient_service_load('tas');
  $result = $service->tas_version($info);
  variable_set('tas_dash_tas_version', $result);
  return $result;
}


function tas_dash_wsclient_get_all_agents($op = 'get', $op2 = 'all_agents', $other_mode = 'url_encode_separator_|',
                                          $apipass = '', $user = '', $pass = '') {
  $service = wsclient_service_load('tas');
  $result = $service->tas_get_all_agents($op, $op2, $other_mode, $apipass, $user, $pass);
  variable_set('tas_dash_all_tas_agents', $result);
  return $result;
}
